
// This file has been generated by the GUI designer. Do not modify.
namespace Open4051
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vboxMain;
		
		private global::Gtk.VBox vboxTop;
		
		private global::Gtk.Label labelMain;
		
		private global::Gtk.VButtonBox vbuttonbox;
		
		private global::Gtk.Button btnNetworkSetting;
		
		private global::Gtk.Button btnCalibrate;
		
		private global::Gtk.Button btnContinue;
		
		private global::Gtk.Frame frameBottom;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.HBox hboxBottom;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textviewLog;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.Button btnNetworkTest;
		
		private global::Gtk.Image imageConnected;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label labelCalibrated;
		
		private global::Gtk.Label labelConnection;
		
		private global::Gtk.Label labelGateway;
		
		private global::Gtk.Label labelIP;
		
		private global::Gtk.Label labelMask;
		
		private global::Gtk.Label labelRemote;
		
		private global::Gtk.Label GtkLabelLog;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Open4051.MainWindow
			this.Name = "Open4051.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Open 4051");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultWidth = 1024;
			this.DefaultHeight = 768;
			// Container child Open4051.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.vboxTop = new global::Gtk.VBox ();
			this.vboxTop.Name = "vboxTop";
			this.vboxTop.Spacing = 6;
			// Container child vboxTop.Gtk.Box+BoxChild
			this.labelMain = new global::Gtk.Label ();
			this.labelMain.HeightRequest = 150;
			this.labelMain.Name = "labelMain";
			this.labelMain.LabelProp = "<b>Open 4051 Display Setup</b>";
			this.labelMain.UseMarkup = true;
			this.labelMain.Justify = ((global::Gtk.Justification)(2));
			this.vboxTop.Add (this.labelMain);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxTop [this.labelMain]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxTop.Gtk.Box+BoxChild
			this.vbuttonbox = new global::Gtk.VButtonBox ();
			this.vbuttonbox.Name = "vbuttonbox";
			this.vbuttonbox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox.Gtk.ButtonBox+ButtonBoxChild
			this.btnNetworkSetting = new global::Gtk.Button ();
			this.btnNetworkSetting.CanFocus = true;
			this.btnNetworkSetting.Name = "btnNetworkSetting";
			this.btnNetworkSetting.UseUnderline = true;
			this.btnNetworkSetting.Label = global::Mono.Unix.Catalog.GetString ("Network Sttings");
			this.vbuttonbox.Add (this.btnNetworkSetting);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox [this.btnNetworkSetting]));
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbuttonbox.Gtk.ButtonBox+ButtonBoxChild
			this.btnCalibrate = new global::Gtk.Button ();
			this.btnCalibrate.CanFocus = true;
			this.btnCalibrate.Name = "btnCalibrate";
			this.btnCalibrate.UseUnderline = true;
			this.btnCalibrate.Label = global::Mono.Unix.Catalog.GetString ("         Calibrate Touchscreen        ");
			this.vbuttonbox.Add (this.btnCalibrate);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox [this.btnCalibrate]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbuttonbox.Gtk.ButtonBox+ButtonBoxChild
			this.btnContinue = new global::Gtk.Button ();
			this.btnContinue.CanFocus = true;
			this.btnContinue.Name = "btnContinue";
			this.btnContinue.UseUnderline = true;
			this.btnContinue.Label = global::Mono.Unix.Catalog.GetString ("Continue");
			this.vbuttonbox.Add (this.btnContinue);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox [this.btnContinue]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxTop.Add (this.vbuttonbox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxTop [this.vbuttonbox]));
			w5.Position = 1;
			this.vboxMain.Add (this.vboxTop);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.vboxTop]));
			w6.Position = 0;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frameBottom = new global::Gtk.Frame ();
			this.frameBottom.HeightRequest = 250;
			this.frameBottom.Name = "frameBottom";
			this.frameBottom.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frameBottom.BorderWidth = ((uint)(2));
			// Container child frameBottom.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(1));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hboxBottom = new global::Gtk.HBox ();
			this.hboxBottom.Name = "hboxBottom";
			this.hboxBottom.Spacing = 6;
			// Container child hboxBottom.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewLog = new global::Gtk.TextView ();
			this.textviewLog.WidthRequest = 200;
			this.textviewLog.Name = "textviewLog";
			this.textviewLog.Editable = false;
			this.textviewLog.CursorVisible = false;
			this.textviewLog.AcceptsTab = false;
			this.GtkScrolledWindow.Add (this.textviewLog);
			this.hboxBottom.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxBottom [this.GtkScrolledWindow]));
			w8.Position = 0;
			// Container child hboxBottom.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table2.WidthRequest = 10;
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.btnNetworkTest = new global::Gtk.Button ();
			this.btnNetworkTest.CanFocus = true;
			this.btnNetworkTest.Name = "btnNetworkTest";
			this.btnNetworkTest.UseUnderline = true;
			this.btnNetworkTest.Label = global::Mono.Unix.Catalog.GetString ("        Network Echo Test        ");
			this.table2.Add (this.btnNetworkTest);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.btnNetworkTest]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.XOptions = ((global::Gtk.AttachOptions)(0));
			w9.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table2.Gtk.Table+TableChild
			this.imageConnected = new global::Gtk.Image ();
			this.imageConnected.Name = "imageConnected";
			this.table2.Add (this.imageConnected);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.imageConnected]));
			w10.TopAttach = ((uint)(6));
			w10.BottomAttach = ((uint)(7));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("IP Address:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w11.XOptions = ((global::Gtk.AttachOptions)(7));
			w11.YOptions = ((global::Gtk.AttachOptions)(7));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Subnet Mask:");
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Gateway:");
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Remote IP:");
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Connection:");
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Calibrated:");
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelCalibrated = new global::Gtk.Label ();
			this.labelCalibrated.Name = "labelCalibrated";
			this.labelCalibrated.LabelProp = global::Mono.Unix.Catalog.GetString ("label13");
			this.table2.Add (this.labelCalibrated);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelCalibrated]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelConnection = new global::Gtk.Label ();
			this.labelConnection.Name = "labelConnection";
			this.labelConnection.LabelProp = global::Mono.Unix.Catalog.GetString ("label12");
			this.table2.Add (this.labelConnection);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelConnection]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelGateway = new global::Gtk.Label ();
			this.labelGateway.Name = "labelGateway";
			this.labelGateway.LabelProp = global::Mono.Unix.Catalog.GetString ("label10");
			this.table2.Add (this.labelGateway);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelGateway]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelIP = new global::Gtk.Label ();
			this.labelIP.Name = "labelIP";
			this.labelIP.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.table2.Add (this.labelIP);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelIP]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.labelMask = new global::Gtk.Label ();
			this.labelMask.Name = "labelMask";
			this.labelMask.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.table2.Add (this.labelMask);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelMask]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelRemote = new global::Gtk.Label ();
			this.labelRemote.Name = "labelRemote";
			this.labelRemote.LabelProp = global::Mono.Unix.Catalog.GetString ("label11");
			this.table2.Add (this.labelRemote);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelRemote]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			this.hboxBottom.Add (this.table2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hboxBottom [this.table2]));
			w23.Position = 1;
			this.GtkAlignment.Add (this.hboxBottom);
			this.frameBottom.Add (this.GtkAlignment);
			this.GtkLabelLog = new global::Gtk.Label ();
			this.GtkLabelLog.Name = "GtkLabelLog";
			this.GtkLabelLog.Xpad = 8;
			this.GtkLabelLog.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Activity Log:</b>");
			this.GtkLabelLog.UseMarkup = true;
			this.frameBottom.LabelWidget = this.GtkLabelLog;
			this.vboxMain.Add (this.frameBottom);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.frameBottom]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.FocusActivated += new global::System.EventHandler (this.OnLoad);
			this.btnNetworkSetting.Clicked += new global::System.EventHandler (this.OnBtnNetworkSettingClicked);
			this.btnCalibrate.Clicked += new global::System.EventHandler (this.OnBtnCalibrateClicked);
		}
	}
}
