
// This file has been generated by the GUI designer. Do not modify.
namespace Open4051
{
	public partial class WindowNetworkSetting
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label labelSetup;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Table table3;
		private global::Gtk.Button btnBackbone;
		private global::Gtk.Button btnCustom;
		private global::Gtk.Entry entryAddress;
		private global::Gtk.Entry entryGateway;
		private global::Gtk.Entry entryGroup;
		private global::Gtk.Entry entryMask;
		private global::Gtk.Entry entryPriority;
		private global::Gtk.Entry entryRemote;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label labelGroup;
		private global::Gtk.Label labelPriority;
		private global::Gtk.DrawingArea drawingarea1;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnSave;
		private global::Gtk.Button btnCancel;
		private global::Gtk.Button btnDefault;
		private global::Gtk.Button btnClear;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Open4051.WindowNetworkSetting
			this.Name = "Open4051.WindowNetworkSetting";
			this.Title = global::Mono.Unix.Catalog.GetString ("WindowNetworkSetting");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultWidth = 1024;
			this.DefaultHeight = 768;
			// Container child Open4051.WindowNetworkSetting.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelSetup = new global::Gtk.Label ();
			this.labelSetup.HeightRequest = 150;
			this.labelSetup.Name = "labelSetup";
			this.labelSetup.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Open 4051 Network Setup</b>");
			this.labelSetup.UseMarkup = true;
			this.vbox4.Add (this.labelSetup);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.labelSetup]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.btnBackbone = new global::Gtk.Button ();
			this.btnBackbone.CanFocus = true;
			this.btnBackbone.Name = "btnBackbone";
			this.btnBackbone.UseUnderline = true;
			this.btnBackbone.Label = global::Mono.Unix.Catalog.GetString ("Backbone");
			this.table3.Add (this.btnBackbone);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnBackbone]));
			w2.XOptions = ((global::Gtk.AttachOptions)(1));
			w2.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table3.Gtk.Table+TableChild
			this.btnCustom = new global::Gtk.Button ();
			this.btnCustom.CanFocus = true;
			this.btnCustom.Name = "btnCustom";
			this.btnCustom.UseUnderline = true;
			this.btnCustom.Label = global::Mono.Unix.Catalog.GetString ("Customize");
			this.table3.Add (this.btnCustom);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnCustom]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(1));
			w3.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table3.Gtk.Table+TableChild
			this.entryAddress = new global::Gtk.Entry ();
			this.entryAddress.CanFocus = true;
			this.entryAddress.Name = "entryAddress";
			this.entryAddress.IsEditable = true;
			this.entryAddress.InvisibleChar = '●';
			this.table3.Add (this.entryAddress);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryAddress]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(0));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryGateway = new global::Gtk.Entry ();
			this.entryGateway.CanFocus = true;
			this.entryGateway.Name = "entryGateway";
			this.entryGateway.IsEditable = true;
			this.entryGateway.InvisibleChar = '●';
			this.table3.Add (this.entryGateway);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryGateway]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(0));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryGroup = new global::Gtk.Entry ();
			this.entryGroup.CanFocus = true;
			this.entryGroup.Name = "entryGroup";
			this.entryGroup.IsEditable = true;
			this.entryGroup.InvisibleChar = '●';
			this.table3.Add (this.entryGroup);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryGroup]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(0));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryMask = new global::Gtk.Entry ();
			this.entryMask.CanFocus = true;
			this.entryMask.Name = "entryMask";
			this.entryMask.IsEditable = true;
			this.entryMask.InvisibleChar = '●';
			this.table3.Add (this.entryMask);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryMask]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(0));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryPriority = new global::Gtk.Entry ();
			this.entryPriority.CanFocus = true;
			this.entryPriority.Name = "entryPriority";
			this.entryPriority.IsEditable = true;
			this.entryPriority.InvisibleChar = '●';
			this.table3.Add (this.entryPriority);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryPriority]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(0));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryRemote = new global::Gtk.Entry ();
			this.entryRemote.CanFocus = true;
			this.entryRemote.Name = "entryRemote";
			this.entryRemote.IsEditable = true;
			this.entryRemote.InvisibleChar = '●';
			this.table3.Add (this.entryRemote);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryRemote]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(0));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("IP Address:");
			this.table3.Add (this.label15);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.label15]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Subnet Mask:");
			this.table3.Add (this.label16);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			// Container child table3.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Gateway:");
			this.table3.Add (this.label17);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.label17]));
			w12.TopAttach = ((uint)(5));
			w12.BottomAttach = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Remote IP Address:");
			this.table3.Add (this.label18);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.label18]));
			w13.TopAttach = ((uint)(6));
			w13.BottomAttach = ((uint)(7));
			// Container child table3.Gtk.Table+TableChild
			this.labelGroup = new global::Gtk.Label ();
			this.labelGroup.Name = "labelGroup";
			this.labelGroup.LabelProp = global::Mono.Unix.Catalog.GetString ("Group(1-99):");
			this.table3.Add (this.labelGroup);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelGroup]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.labelPriority = new global::Gtk.Label ();
			this.labelPriority.Name = "labelPriority";
			this.labelPriority.LabelProp = global::Mono.Unix.Catalog.GetString ("Priority(0-10):");
			this.table3.Add (this.labelPriority);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.labelPriority]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add (this.table3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.table3]));
			w16.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.hbox1.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawingarea1]));
			w17.Position = 1;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w18.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.HeightRequest = 80;
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString ("Save / Apply");
			this.hbuttonbox1.Add (this.btnSave);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnSave]));
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancel = new global::Gtk.Button ();
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbuttonbox1.Add (this.btnCancel);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnCancel]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDefault = new global::Gtk.Button ();
			this.btnDefault.CanFocus = true;
			this.btnDefault.Name = "btnDefault";
			this.btnDefault.UseUnderline = true;
			this.btnDefault.Label = global::Mono.Unix.Catalog.GetString ("Load Default");
			this.hbuttonbox1.Add (this.btnDefault);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnDefault]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnClear = new global::Gtk.Button ();
			this.btnClear.CanFocus = true;
			this.btnClear.Name = "btnClear";
			this.btnClear.UseUnderline = true;
			this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbuttonbox1.Add (this.btnClear);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnClear]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox4.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox1]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.btnCustom.Clicked += new global::System.EventHandler (this.OnBtnCustomClicked);
			this.btnBackbone.Clicked += new global::System.EventHandler (this.OnBtnBackboneClicked);
			this.btnSave.Clicked += new global::System.EventHandler (this.OnBtnSaveClicked);
			this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
			this.btnDefault.Clicked += new global::System.EventHandler (this.OnBtnDefaultClicked);
			this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
		}
	}
}
