
// This file has been generated by the GUI designer. Do not modify.
namespace Open4051
{
	public partial class ToolBarWindow
	{
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnCloseAll;
		private global::Gtk.Button btnKeyboard;
		private global::Gtk.Button btnCloseBrowser;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Open4051.ToolBarWindow
			this.Name = "Open4051.ToolBarWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ToolBarWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child Open4051.ToolBarWindow.Gtk.Container+ContainerChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Spacing = 4;
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnCloseAll = new global::Gtk.Button ();
			this.btnCloseAll.CanFocus = true;
			this.btnCloseAll.Name = "btnCloseAll";
			this.btnCloseAll.UseUnderline = true;
			this.btnCloseAll.BorderWidth = ((uint)(6));
			// Container child btnCloseAll.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Button);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Unix.Catalog.GetString ("_Close All");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.btnCloseAll.Add (w1);
			this.hbuttonbox1.Add (this.btnCloseAll);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnCloseAll]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnKeyboard = new global::Gtk.Button ();
			this.btnKeyboard.CanFocus = true;
			this.btnKeyboard.Name = "btnKeyboard";
			this.btnKeyboard.UseUnderline = true;
			this.btnKeyboard.BorderWidth = ((uint)(6));
			// Container child btnKeyboard.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Button);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Show Keyboard");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.btnKeyboard.Add (w10);
			this.hbuttonbox1.Add (this.btnKeyboard);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnKeyboard]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnCloseBrowser = new global::Gtk.Button ();
			this.btnCloseBrowser.CanFocus = true;
			this.btnCloseBrowser.Name = "btnCloseBrowser";
			this.btnCloseBrowser.UseUnderline = true;
			this.btnCloseBrowser.BorderWidth = ((uint)(6));
			// Container child btnCloseBrowser.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-undo", global::Gtk.IconSize.Menu);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w23.LabelProp = global::Mono.Unix.Catalog.GetString ("Close Browser");
			w23.UseUnderline = true;
			w20.Add (w23);
			w19.Add (w20);
			this.btnCloseBrowser.Add (w19);
			this.hbuttonbox1.Add (this.btnCloseBrowser);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnCloseBrowser]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.hbuttonbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 416;
			this.DefaultHeight = 76;
			this.Show ();
			this.btnCloseAll.Clicked += new global::System.EventHandler (this.OnBtnCloseAllClicked);
			this.btnKeyboard.Clicked += new global::System.EventHandler (this.OnBtnKeyboardClicked);
			this.btnCloseBrowser.Clicked += new global::System.EventHandler (this.OnBtnCloseBrowserClicked);
		}
	}
}
